### ISSUE TITLE
[Bug] Non empty slots are overridden by GUIFiller.

### ISSUE THREAD

**Issue by Lorenzo0111** [TriumphTeam/gui#17]
GuiFiller is bugged if you try to fill the border of a GUI because it replaces all existing slots without checking for existing items.

**Comment by ipsk** [comment]
It isn't really a bug, it's intended. The filling is not intended to be used *after* the items are set, it should only be used once as the GUI is being set up.

**Comment by Lorenzo0111** [comment]
ok
